import { describe, expect, it } from "vitest";
import { blueskyEvidence, hasAiDisclosure, mastodonDisclosureText, mastodonEvidence, socialDay } from "./social-contract";

const blue = (text: string) => ({ $type: "message", payload: { $type: "network.bsky.jetstream.subscribeEvents#commit", seq: 123,
  did: "did:plc:example", rkey: "example-record", time: "2026-09-11T03:00:01.123456Z", operation: "create", collection: "app.bsky.feed.post",
  record: { $type: "app.bsky.feed.post", text, createdAt: "2000-01-01T00:00:00Z" } } });
const mastodon = (content: string, bot = false) => ({ id: "123", content, account: { bot }, created_at: "2026-09-11T02:50:00Z", visibility: "public", reblog: null, in_reply_to_id: null });

describe("social disclosure evidence", () => {
  it("recognizes narrow direct English disclosures without claiming authorship", () => {
    expect(hasAiDisclosure("This post was written by ChatGPT.")).toBe(true);
    expect(hasAiDisclosure("I used AI to create this image.")).toBe(true);
    expect(hasAiDisclosure("Disclosure: This image is AI-generated.")).toBe(true);
    expect(hasAiDisclosure("A new photo.\nThis caption was drafted using Claude.")).toBe(true);
  });
  it("does not count ordinary mentions, hashtags, negations or quoted disclosures", () => {
    for (const text of ["ChatGPT is popular", "#aiart #AI", "This post was not written by ChatGPT.", "I did not use AI to write this post.",
      'He said: This post was written by ChatGPT.', '"This post was written by ChatGPT."', "> This post was written by ChatGPT.", "Does AI write posts?"]) {
      expect(hasAiDisclosure(text), text).toBe(false);
    }
  });
  it("ignores markup targets, quoted blocks and scripts while keeping visible disclosure text", () => {
    const html = '<blockquote><p>This post was written by ChatGPT.</p></blockquote><script>This post was written by ChatGPT.</script><p><a title="This post was written by ChatGPT.">ordinary link</a></p>';
    expect(hasAiDisclosure(mastodonDisclosureText(html))).toBe(false);
    expect(hasAiDisclosure(mastodonDisclosureText("<p>I used AI to write this post.</p>"))).toBe(true);
  });
  it("treats bot flags separately and allows overlap with disclosure", () => {
    const onlyBot = mastodonEvidence(mastodon("ordinary post", true), "https://mastodon.social");
    expect(onlyBot).toMatchObject({ kind: "post", evidence: { aiDisclosure: false, automatedAccount: true } });
    expect(mastodonEvidence(mastodon("<p>This image was generated by AI.</p>", true), "https://mastodon.social"))
      .toMatchObject({ evidence: { aiDisclosure: true, automatedAccount: true } });
    expect(mastodonEvidence({ ...mastodon("x"), account: { bot: "true" } }, "https://mastodon.social").kind).toBe("invalid");
  });
  it("excludes boosts, replies and nonpublic statuses", () => {
    const post = mastodon("This post was written by ChatGPT.");
    for (const row of [{ ...post, reblog: post }, { ...post, in_reply_to_id: "1" }, { ...post, visibility: "private" }]) {
      expect(mastodonEvidence(row, "https://mastodon.social").kind).toBe("excluded");
    }
  });
});

describe("Jetstream v2 framing", () => {
  it("accepts the canonical envelope and preserves publisher display time, not client creation time", () => {
    expect(blueskyEvidence(blue("This post was written by ChatGPT."))).toMatchObject({ kind: "post", evidence: {
      publisherAt: "2026-09-11T03:00:01.123Z", aiDisclosure: true, automatedAccount: false,
    } });
  });
  it("rejects v1 frames and terminal errors rather than recording a successful zero", () => {
    expect(blueskyEvidence({ kind: "commit", commit: { operation: "create" } }).kind).toBe("invalid");
    expect(blueskyEvidence({ $type: "error", error: "ConsumerTooSlow" }).kind).toBe("error");
    const invalid = blue("post");
    invalid.payload.time = "not a date";
    expect(blueskyEvidence(invalid).kind).toBe("invalid");
  });
  it("excludes mutations of existing posts, replies and other collections", () => {
    const event = blue("post");
    expect(blueskyEvidence({ ...event, payload: { ...event.payload, operation: "delete" } }).kind).toBe("excluded");
    expect(blueskyEvidence({ ...event, payload: { ...event.payload, record: { ...event.payload.record, reply: {} } } }).kind).toBe("excluded");
    expect(blueskyEvidence({ ...event, payload: { ...event.payload, collection: "app.bsky.feed.like" } }).kind).toBe("excluded");
  });
  it("uses the UTC sampling date", () => {
    expect(socialDay(new Date("2026-09-10T20:00:00-07:00"))).toBe("2026-09-11");
  });
});
