// Shared by the historical census reader and deterministic local QA fixtures.
/** Crawler tokens counted in every robots.txt sample; `*` is the catch-all group. */
export const ROBOTS_TOKENS = [
  "GPTBot",
  "ChatGPT-User",
  "OAI-SearchBot",
  "ClaudeBot",
  "anthropic-ai",
  "Claude-Web",
  "Claude-User",
  "Claude-SearchBot",
  "CCBot",
  "Google-Extended",
  "PerplexityBot",
  "Perplexity-User",
  "Bytespider",
  "Applebot-Extended",
  "Amazonbot",
  "meta-externalagent",
  "FacebookBot",
  "cohere-ai",
  "Diffbot",
  "ImagesiftBot",
  "omgili",
  "YouBot",
  "DuckAssistBot",
  "AI2Bot",
  "PetalBot",
  "Googlebot",
  "Bingbot",
  "*",
] as const;
