-- Original application schema at commit 8822e28f3950f8eb9e342c1989b3bf3bbd485e5b.
-- Generated by drizzle-kit solely for isolated QA initialization and migration regression.
CREATE TABLE "agent_sightings" (
	"id" serial PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"token" text NOT NULL,
	"operator" text,
	"fn" text,
	"url" text,
	"first_seen" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "commons_ai_uploads" (
	"pageid" bigint PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"ts" timestamp with time zone NOT NULL,
	"category" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "external_series" (
	"source" text NOT NULL,
	"series" text NOT NULL,
	"period" text NOT NULL,
	"value" double precision NOT NULL,
	"lo" double precision,
	"hi" double precision,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "external_series_source_series_period_pk" PRIMARY KEY("source","series","period")
);
--> statement-breakpoint
CREATE TABLE "forum_daily" (
	"day" date PRIMARY KEY NOT NULL,
	"posts" integer DEFAULT 0 NOT NULL,
	"agents" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "forum_posts" (
	"id" text PRIMARY KEY NOT NULL,
	"agent" text NOT NULL,
	"agent_id" text,
	"ts" timestamp with time zone NOT NULL,
	"title" text NOT NULL,
	"snippet" text,
	"url" text NOT NULL,
	"board" text,
	"score" integer,
	"comments" integer
);
--> statement-breakpoint
CREATE TABLE "gh_archive_daily" (
	"day" date NOT NULL,
	"kind" text NOT NULL,
	"key" text NOT NULL,
	"value" integer NOT NULL,
	"hours" integer NOT NULL,
	CONSTRAINT "gh_archive_daily_day_kind_key_pk" PRIMARY KEY("day","kind","key")
);
--> statement-breakpoint
CREATE TABLE "gh_archive_hourly" (
	"hour" text NOT NULL,
	"kind" text NOT NULL,
	"key" text NOT NULL,
	"value" integer NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "gh_archive_hourly_hour_kind_key_pk" PRIMARY KEY("hour","kind","key")
);
--> statement-breakpoint
CREATE TABLE "github_daily" (
	"day" date NOT NULL,
	"agent" text NOT NULL,
	"prs" integer DEFAULT 0 NOT NULL,
	"tier" text NOT NULL,
	"final" boolean DEFAULT false NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "github_daily_day_agent_pk" PRIMARY KEY("day","agent")
);
--> statement-breakpoint
CREATE TABLE "github_events" (
	"id" bigint PRIMARY KEY NOT NULL,
	"agent" text NOT NULL,
	"repo" text NOT NULL,
	"number" integer NOT NULL,
	"title" text NOT NULL,
	"url" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "guestbook_notes" (
	"id" serial PRIMARY KEY NOT NULL,
	"ts" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	"operator" text,
	"purpose" text,
	"note" text NOT NULL,
	"ua" text NOT NULL,
	"agent_slug" text,
	"signed" boolean DEFAULT false NOT NULL,
	"signature_agent" text,
	"ip_prefix" text,
	"hidden" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ingest_runs" (
	"id" serial PRIMARY KEY NOT NULL,
	"source" text NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone,
	"ok" boolean DEFAULT false NOT NULL,
	"cursor" text,
	"stats" jsonb,
	"error" text
);
--> statement-breakpoint
CREATE TABLE "ip_ranges" (
	"id" serial PRIMARY KEY NOT NULL,
	"source" text NOT NULL,
	"operator" text NOT NULL,
	"cidr" text NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mcp_servers" (
	"name" text PRIMARY KEY NOT NULL,
	"title" text,
	"description" text,
	"url" text,
	"published_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"first_seen" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "osm_changesets" (
	"id" bigint PRIMARY KEY NOT NULL,
	"ts" timestamp with time zone NOT NULL,
	"user" text,
	"editor" text,
	"ai_kind" text NOT NULL,
	"changes" integer,
	"comment" text,
	"url" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "osm_daily" (
	"day" date PRIMARY KEY NOT NULL,
	"sampled" integer DEFAULT 0 NOT NULL,
	"ai_assisted" integer DEFAULT 0 NOT NULL,
	"by_editor" jsonb
);
--> statement-breakpoint
CREATE TABLE "traffic_daily" (
	"day" date NOT NULL,
	"category" text NOT NULL,
	"count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "traffic_daily_day_category_pk" PRIMARY KEY("day","category")
);
--> statement-breakpoint
CREATE TABLE "visits" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"ts" timestamp with time zone DEFAULT now() NOT NULL,
	"day" date NOT NULL,
	"path" text NOT NULL,
	"method" text NOT NULL,
	"ua" text NOT NULL,
	"agent_slug" text,
	"agent_name" text,
	"operator" text,
	"category" text NOT NULL,
	"verified" boolean,
	"verified_by" text,
	"signed" boolean DEFAULT false NOT NULL,
	"signature_agent" text,
	"ip_prefix" text,
	"ip_hash" text,
	"country" char(2),
	"referer" text,
	"robots_violation" boolean DEFAULT false NOT NULL,
	"trap_token" text
);
--> statement-breakpoint
CREATE TABLE "watched_prs" (
	"id" text PRIMARY KEY NOT NULL,
	"source_id" text NOT NULL,
	"platform" text NOT NULL,
	"kind" text NOT NULL,
	"title" text NOT NULL,
	"url" text NOT NULL,
	"actor_login" text,
	"actor_id" bigint,
	"agent_id" text,
	"attribution" text NOT NULL,
	"repository" text,
	"state" text,
	"created_at" timestamp with time zone NOT NULL,
	"source_updated_at" timestamp with time zone,
	"last_observed_at" timestamp with time zone,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"evidence" text,
	"body_excerpt" text
);
--> statement-breakpoint
CREATE TABLE "watched_repos" (
	"repo" text PRIMARY KEY NOT NULL,
	"source" text DEFAULT 'seed' NOT NULL,
	"first_seen" timestamp with time zone DEFAULT now() NOT NULL,
	"last_polled_at" timestamp with time zone,
	"last_pr_at" timestamp with time zone,
	"pr_count_30d" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "watched_signals" (
	"id" text PRIMARY KEY NOT NULL,
	"activity_id" text NOT NULL,
	"rule_id" text NOT NULL,
	"excerpt" text,
	"status" text DEFAULT 'unreviewed' NOT NULL,
	"reason" text,
	"url" text,
	"reviewed_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "wiki_daily" (
	"day" date NOT NULL,
	"wiki" text NOT NULL,
	"total" integer,
	"bot" integer,
	"anon" integer,
	CONSTRAINT "wiki_daily_day_wiki_pk" PRIMARY KEY("day","wiki")
);
--> statement-breakpoint
CREATE TABLE "wiki_edits" (
	"wiki" text NOT NULL,
	"rcid" bigint NOT NULL,
	"rev_id" bigint,
	"ts" timestamp with time zone NOT NULL,
	"title" text NOT NULL,
	"user" text NOT NULL,
	"comment" text,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"tier" smallint NOT NULL,
	"signals" text[] DEFAULT '{}' NOT NULL,
	"old_len" integer,
	"new_len" integer,
	"url" text NOT NULL,
	CONSTRAINT "wiki_edits_wiki_rcid_pk" PRIMARY KEY("wiki","rcid")
);
--> statement-breakpoint
CREATE TABLE "wiki_tag_watch" (
	"wiki" text NOT NULL,
	"tag" text NOT NULL,
	"hitcount" integer DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"first_seen" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "wiki_tag_watch_wiki_tag_pk" PRIMARY KEY("wiki","tag")
);
--> statement-breakpoint
CREATE TABLE "wikidata_bot_edits" (
	"revid" bigint PRIMARY KEY NOT NULL,
	"user" text NOT NULL,
	"user_id" bigint,
	"title" text NOT NULL,
	"ts" timestamp with time zone NOT NULL,
	"comment" text,
	"size" integer
);
--> statement-breakpoint
CREATE UNIQUE INDEX "agent_sightings_kind_token_uq" ON "agent_sightings" USING btree ("kind","token");--> statement-breakpoint
CREATE INDEX "agent_sightings_first_seen_idx" ON "agent_sightings" USING btree ("first_seen" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "commons_ai_uploads_ts_idx" ON "commons_ai_uploads" USING btree ("ts" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "forum_posts_ts_idx" ON "forum_posts" USING btree ("ts" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "gh_archive_daily_kind_day_idx" ON "gh_archive_daily" USING btree ("kind","day" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "github_events_created_idx" ON "github_events" USING btree ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "github_events_agent_created_idx" ON "github_events" USING btree ("agent","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "guestbook_ts_idx" ON "guestbook_notes" USING btree ("ts" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "ingest_runs_source_started_idx" ON "ingest_runs" USING btree ("source","started_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "ip_ranges_source_cidr_uq" ON "ip_ranges" USING btree ("source","cidr");--> statement-breakpoint
CREATE INDEX "ip_ranges_source_idx" ON "ip_ranges" USING btree ("source");--> statement-breakpoint
CREATE INDEX "mcp_servers_published_idx" ON "mcp_servers" USING btree ("published_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "osm_changesets_ts_idx" ON "osm_changesets" USING btree ("ts" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "visits_ts_idx" ON "visits" USING btree ("ts" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "visits_agent_ts_idx" ON "visits" USING btree ("agent_slug","ts" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "visits_day_cat_idx" ON "visits" USING btree ("day","category");--> statement-breakpoint
CREATE INDEX "watched_prs_created_idx" ON "watched_prs" USING btree ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "watched_prs_agent_created_idx" ON "watched_prs" USING btree ("agent_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "watched_prs_repo_idx" ON "watched_prs" USING btree ("repository");--> statement-breakpoint
CREATE INDEX "wiki_edits_ts_idx" ON "wiki_edits" USING btree ("ts" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "wiki_edits_wiki_tier_ts_idx" ON "wiki_edits" USING btree ("wiki","tier","ts" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "wikidata_bot_edits_ts_idx" ON "wikidata_bot_edits" USING btree ("ts" DESC NULLS LAST);