import { sql } from "drizzle-orm";
import { githubDaily } from "@/lib/db/schema";
import { daysAgo } from "@/lib/format";
import { type Job, timeLeft } from "./common";
import { canCall, RateLimited, search } from "./github";

/**
 * Text signatures across all of GitHub, counted per day with the search API.
 * These are "self-identified" rung: a tool is named, autonomy is not established.
 * Search phrase matching is loose, so treat values as a trend, not a census.
 */
export const SIGNATURE_QUERIES = [
  { key: "sig-claude-code", label: "PRs: Generated with Claude Code", q: '"Generated with Claude Code" in:body is:pr' },
  { key: "sig-copilot-coauthor", label: "PRs: Co-authored-by Copilot", q: '"Co-authored-by: Copilot" in:body is:pr' },
  { key: "sig-cursor", label: "PRs: Made with Cursor", q: '"Made with Cursor" in:body is:pr' },
  { key: "sig-codex", label: "PRs: Codex attribution", q: '"Generated by Codex" in:body is:pr' },
  { key: "sig-devin", label: "PRs: Devin co-author", q: '"co-authored-by: devin-ai" in:body is:pr' },
  { key: "sig-aider", label: "PRs: aider commits", q: '"aider:" in:title is:pr' },
] as const;

export const githubSignaturesJob: Job = async (ctx) => {
  if (!process.env.GITHUB_TOKEN) return { stats: { skipped: "GITHUB_TOKEN not set" } };
  const stats: Record<string, unknown> = { queries: 0 };
  let partial = false;
  const days = [daysAgo(1), daysAgo(2), daysAgo(3)];
  try {
    for (const day of days) {
      for (const s of SIGNATURE_QUERIES) {
        if (!canCall(ctx) || timeLeft(ctx) < 10_000) {
          partial = true;
          break;
        }
        const body = await search(`${s.q} created:${day}`);
        stats.queries = (stats.queries as number) + 1;
        await ctx.db
          .insert(githubDaily)
          .values({ day, agent: s.key, prs: body.total_count ?? 0, tier: "text-signature", final: day !== daysAgo(1), fetchedAt: new Date() })
          .onConflictDoUpdate({ target: [githubDaily.day, githubDaily.agent], set: { prs: sql`excluded.prs`, final: sql`excluded.final`, fetchedAt: new Date() } });
      }
      if (partial) break;
    }
  } catch (err) {
    if (err instanceof RateLimited) {
      stats.rateLimitedUntil = new Date(err.resetAt).toISOString();
      partial = true;
    } else throw err;
  }
  return { stats, partial };
};
